// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deletefollow.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteFeedFollow = `-- name: DeleteFeedFollow :execrows
DELETE FROM feed_follows
Where feed_follows.user_id = $1
AND feed_follows.feed_id IN ( 
	SELECT id FROM feeds WHERE url = $2
)
`

type DeleteFeedFollowParams struct {
	UserID uuid.UUID
	Url    string
}

func (q *Queries) DeleteFeedFollow(ctx context.Context, arg DeleteFeedFollowParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteFeedFollow, arg.UserID, arg.Url)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
