// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: getpostbyurl.sql

package database

import (
	"context"
)

const getPostByURL = `-- name: GetPostByURL :one
SELECT id, created_at, updated_at, seen_at, title, url, description, content, published_at, feed_id FROM posts
WHERE url = $1
`

func (q *Queries) GetPostByURL(ctx context.Context, url string) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPostByURL, url)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SeenAt,
		&i.Title,
		&i.Url,
		&i.Description,
		&i.Content,
		&i.PublishedAt,
		&i.FeedID,
	)
	return i, err
}
