// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: getrandomposts.sql

package database

import (
	"context"
)

const getRandomPosts = `-- name: GetRandomPosts :many
SELECT id, created_at, updated_at, seen_at, title, url, description, content, published_at, feed_id FROM posts
ORDER BY (seen_at IS NOT NULL), seen_at ASC, RANDOM()
LIMIT $1
`

func (q *Queries) GetRandomPosts(ctx context.Context, limit int32) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, getRandomPosts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SeenAt,
			&i.Title,
			&i.Url,
			&i.Description,
			&i.Content,
			&i.PublishedAt,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
