// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: markfeedfetched.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const markFeedFetched = `-- name: MarkFeedFetched :execrows
UPDATE feeds
SET updated_at = $2,
last_fetched_at = $2
WHERE id = $1
`

type MarkFeedFetchedParams struct {
	ID        uuid.UUID
	UpdatedAt time.Time
}

func (q *Queries) MarkFeedFetched(ctx context.Context, arg MarkFeedFetchedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markFeedFetched, arg.ID, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
