// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: markpostread.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const markPostRead = `-- name: MarkPostRead :exec
UPDATE posts
SET seen_at = $2
WHERE id = $1
`

type MarkPostReadParams struct {
	ID     uuid.UUID
	SeenAt sql.NullTime
}

func (q *Queries) MarkPostRead(ctx context.Context, arg MarkPostReadParams) error {
	_, err := q.db.ExecContext(ctx, markPostRead, arg.ID, arg.SeenAt)
	return err
}
